package view;

public enum MenuCommand {
    EXIT, LOGIN, REGISTER, ADD_USER, VIEW_USER, EDIT_USER, DELETE_USER, LIST_ALL_USERS,
    ADD_QUIZ, VIEW_QUIZ, EDIT_QUIZ, DELETE_QUIZ,
    ADD_QUESTION, VIEW_QUESTION, EDIT_QUESTION, DELETE_QUESTION,
    ADD_ANSWER, VIEW_ANSWER, EDIT_ANSWER, DELETE_ANSWER
}
